# Generated by Django 3.0.5 on 2020-04-11 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200411_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Deadline'),
        ),
    ]
